### ISSUE TITLE
arduino 1.8

### ISSUE THREAD

**Issue by cnc4less** [MarkusLange/RTCDue#1]
tried it and could not not make work with arduino 1.8 , serial.begin is not working ? please advise

**Comment by MarkusLange** [comment]
Hi cnc4less,

can you give me some more to look at, the sketch and what you try to do?

**Comment by colesnicov** [comment]
@cnc4less 

You may need to change this:

```
/* Create an rtc object and select Slowclock source */
//RTCDue rtc(RC);
RTCDue rtc(XTAL);
```

 to this:

```
/* Create an rtc object and select Slowclock source */
RTCDue rtc(RC);
//RTCDue rtc(XTAL);
```

**Comment by Electromania** [comment]
i tried it but it is not working. i do not get anything on serial port. 
i used your old rtc library too both have same problem. 

earlier i used your old library and it worked fine on another dueboard. but same sketch is not workingwhen my arduino was upgraded to 1.8  any idea for trouble shooting ?

**Comment by MarkusLange** [comment]
There are 2 USB-Ports did you use the Arduino Due (ProgrammingPort, **Serial**) or the Arduino Due (NativeUSBPort, **SerialUSB**) they use different Serials. Labeled on the bottom.

**Comment by Electromania** [comment]
I tried both ports, and also tried to change from XTAL to RC as shown below.

RTCDue rtc(RC);
//RTCDue rtc(XTAL);

None of your example codes work :(.  
i noticed i do not have 32Mhz crystal , but still i believe it should work with internal RC oscillator ? or not ?

**Comment by Electromania** [comment]
i had made a short project using your old library , that worked perfectly. 
https://www.youtube.com/watch?v=SPk8xxSgUxk  
but same sketch now is not working on this new board ? and also any of your example sketches. it compiles , uploads and nothing pops up on serial port.

**Comment by MarkusLange** [comment]
What Port did you use?
[https://www.arduino.cc/en/Guide/ArduinoDue#toc13](url)

**Comment by Electromania** [comment]
quick update , now i tried your other two example sketches - RTCDue_Unixtime_Compilertime  and RTCDue_AlarmDate_Sample and RTCDue_AlarmTime_Sample these two sketches are showing time on serial port. 
   but your RTCDue_Simple_Sample  is not showing anything. why ?

**Comment by Electromania** [comment]
your link is not working.
to answer your question i used programming port. and also tired with Native USB port.

**Comment by MarkusLange** [comment]
No idea atm. I will look at it later

**Comment by Electromania** [comment]
ok thanks. i will try if i can solder the 32Mhz xtal and C23 C24 on the board, just to be sure that i have Complete board.

**Comment by MarkusLange** [comment]
So I tested it it takes some time but the time shows up.

**Comment by Electromania** [comment]
thanks.i tested too.it works after some time.

**Comment by MarkusLange** [comment]
It takes longer because, every part of time and day is written separate into the register and the next part is done if the register verified its writing so you wait in setup until it's done I will make a notice inside the example about it.
