### ISSUE TITLE
Broken Include for RTCDue.h

### ISSUE THREAD

**Issue by awwen** [MarkusLange/RTCDue#6]
Looks like there's a broken include @ RTCDue.h

`#include <include/rtc.h>`

**Comment by MarkusLange** [comment]
Did you compile it with an error?

Can you post the compiler message with which Arduino IDE Version?

**Comment by aarestcode** [comment]
I think the compiler version was the issue.

Followed instructions to install required cores for newer compiler version [here](https://www.arduino.cc/en/Guide/ArduinoDue) and was able to compile.

**Comment by awwen** [comment]
I think compiler version was the issue.

Changed version and followed instructions to install core [here](https://www.arduino.cc/en/Guide/ArduinoDue).

Worked after that.
