### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by PitrsCZ** [MarkusLange/RTCDue#7]
I need to know what this library is used for. I uploaded the RTCDue_Simple_Sample trial program to my arduino and nothing was written out on the serial monitor and the board has not been communicating ever since. The programing port logs in but nothing can be loaded into the board. Can you please help me?

**Comment by MarkusLange** [comment]
What Board did you use, has to be an Arduino Due. Does it have an Crystal?

**Comment by PitrsCZ** [comment]
Sorry. I am a beginner. I'd rather attach a photo.
![IMG_20200421_171133](https://user-images.githubusercontent.com/64060152/79883516-4c162500-83f4-11ea-9b6d-b9d52eeeb7d3.jpg)

**Comment by MarkusLange** [comment]
Thanks that helps a lot.
Your Board has no Crystal for the Clock you need to set it this way
```
/* Create an rtc object ans choose SlowClock source*/
RTCDue rtc(RC);
//RTCDue rtc(XTAL);
```
![ArduinoDue](https://user-images.githubusercontent.com/1971238/79886735-c5fcdd00-83f9-11ea-9521-c939ff0362f2.png)

**Comment by PitrsCZ** [comment]
Thank you for your quick answers. The problem is that the board can no longer do anything to record. Native port does not log in at all and programing port prints an error while loading the program. Is it possible to restart the board? The RESET button does nothing.

**Comment by MarkusLange** [comment]
The Due has an Build-in hardcoded Bootloader, so there is nothing to flash. What errors are shown? If the Nativ-Port does not connect may your Port is not correct connected with the inf-File

**Comment by PitrsCZ** [comment]
This is an error message for uploading via the programming port:
--------------------------------------
Arduino: 1.8.12 (Windows 10), Board: "Arduino Due (Programming Port)"

Sketch uses 24560 bytes (4%) of program storage space. Maximum is 524288 bytes.
An error occurred while uploading the sketch
No device found on COM9

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
-----------------------------------------

Native port is not recognized by Windows
Thank you for your time

**Comment by MarkusLange** [comment]
May we got more with verbose on. Perhaps you share your error message on the Arduino forum for help

**Comment by PitrsCZ** [comment]
I put the board back into operation. I used the procedure from the arduino.cc site and the procedure would be this: The manual procedure requires holding down the delete button for a second, pressing the upload button in the IDE, and then the reset button.
After this procedure, the board woke up again and normal communication is possible.
Thank you again for your time.

**Comment by MarkusLange** [comment]
You're welcome
